defmodule Mark.Repo.Migrations.AddWorkoutsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workouts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :data, :map, default: %{}
    end
  end

  def down do
    drop table(:workouts)
  end
end
