defmodule Mark.Repo.Migrations.CreateExercises do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sets) do
      add :exercise_id, :uuid
    end

    create table(:exercises, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sets) do
      modify :exercise_id,
             references(:exercises,
               column: :id,
               name: "sets_exercise_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:exercises) do
      add :name, :text, null: false
      add :equipment, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:exercises) do
      remove :inserted_at
      remove :equipment
      remove :name
    end

    drop constraint(:sets, "sets_exercise_id_fkey")

    alter table(:sets) do
      modify :exercise_id, :uuid
    end

    drop table(:exercises)

    alter table(:sets) do
      remove :exercise_id
    end
  end
end
